apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:p/msNtOJLTE9ka7rks8Zrw==,iv:l42V77pvHP9xEnxsTN1IHbtxLY7A/RGeSlBu+BEGc6k=,tag:QR7JTACCrjz3mEUCqV3IDA==,type:str]
    admin-user: ENC[AES256_GCM,data:4RTE/HouwBo=,iv:3ThGbftWJMl6B7N7/9Eo/cxvad++EjDyeptXOpZb530=,tag:GmXoBPHZOq+IkGtPNUL+ug==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    age:
        - recipient: age19xqs7kfl0h4gpheaurgpxjtadhfe6fdxxdprcl4tj9arrd5695wqjkpr4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaXZWVDV4dEV0aXE5MGpa
            c2E4NkxFQUJCNDYzbTUzcThJWDZGenBicmgwCjdJSFIxcmpQNXJzUC9nbnhXNHVR
            ZzhwZVNVWDNWOHVRTmF5SWFydThyMlkKLS0tIEo2eDRwem5UZGdVc050V3p4UEY5
            Mlg2bGxpS0lYNFF0dUExeDlidFJuRzgK3D0Qzm3vcXcXF0d48ScEIYaUJWfXd28S
            HJubhFJ2+HMl0BSj+6ccThtbBCSw0RYY6JPXe25wGPIJh1NWyi97Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:46:19Z"
    mac: ENC[AES256_GCM,data:6AhJWZsyoVfCCP1uVOXW13I08T/fvLikvgDQuBTlgwgxesRwPa9bSPSAmDF4TZ+QUFulDKqleOhlE7NfEmYLxYiPYrkG0rjnXwvZ8GcFWjICa1u3dCdWkqqRE3v+6O4iOOO/qKgzuCGaXbmnsBkdTeZgYfDbMxVT5N1Rk8cUHkY=,iv:Fup1MUn1wa+HaEZ2KgsvHCriKUNbkguvNjzAbKuRfFk=,tag:+74fzaLTpIW1kWaZTwqh/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
