apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:7Hhhy7oNDG+ie9OPN2/lXA==,iv:ELvmyE3SqNW4XnKgbNJT/NSIXp7nISOcO1yz/j0uOmY=,tag:Re6kpiLjGOQHo6hZqTJYbQ==,type:str]
    admin-user: ENC[AES256_GCM,data:9HRkQ0AcVQU=,iv:B7MBFswMcUcpVFgRye5KiRtMjHQTNJ/yvvtNF51+Sas=,tag:685292FJu4rnP5mKf3M4+Q==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
sops:
    age:
        - recipient: age19xqs7kfl0h4gpheaurgpxjtadhfe6fdxxdprcl4tj9arrd5695wqjkpr4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa3M3OHZIMEFlcjRxSnhJ
            L1kzcE8xTlF0YWNSeEZzQjh4YUQ3aklYaGh3ClhJaFRvbXI3aHZ6MldZeThNNWNv
            VWEvTlI5QnhDckN6ZS9jY1A2eFF4UWcKLS0tIE1NL1RjU2lQbGZVUHhOam5FRHVW
            L21NQWFtTjZxbnJ3cEpRemwyWkF4T2cK7gdc+4U3Dj9TmSPpH9qRHWySrp8TFpsd
            UCd+HrziJ8xUncJdXAIoggGhlgoNM6PXbeeR0BBnSwcshQClV4GFjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T13:44:47Z"
    mac: ENC[AES256_GCM,data:BAmmhbUsy2w2YPisj+mc6oq1HEbfLbwjIeJBHS7IhglFUYHwo0qxqljlhWLBC0MOj/yHQXjVIDMIAtidhjF5QfEwo8yyRqBSTe0jCAP/0SSoDANU6/x5Xksj8X6ifEwrbXFIgfyOYeLINRXfkOib5c/SsCA/SU9inf5eWIPgNSs=,iv:B8UFKLx7vwsrzA5oTEmxpx+9J5zKX2S83VFEqAMotdk=,tag:N9EeYYylTkC23CwYnMfDBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
